/**
 * Record shapes written to .lazycop/ as append-only JSONL.
 * Every record carries a `kind` discriminant for exhaustive switch.
 * Shapes match the Contracts section of docs/product/LazyCop — Two-Way Quiz Design.md.
 */

export type LazycopRecord =
  | EventRecord
  | CardRecord
  | AnswerRecord
  | MessageRecord
  | ReplyRecord;

/** A Bob tool call event logged from a hook. */
export interface EventRecord {
  kind: "event";
  ts: string;
  tool: string;
  /** File path the tool operated on, if applicable. */
  path?: string;
  /** Unified patch, if the tool produced a diff. */
  patch?: string;
}

export type CardType =
  | "interpretation"
  | "assumption"
  | "predict_move"
  | "read_hunk"
  | "hidden_assumption"
  | "decision_review";

/** One selectable option on a card. The option whose id is "bob" is Bob's claim. */
export interface CardOption {
  id: string;
  text: string;
}

/** A quiz card generated for the developer. */
export interface CardRecord {
  kind: "card";
  id: string;
  type: CardType;
  /** The question shown to the developer. */
  question: string;
  /** Bob's claim text (also the text of the "bob" option). */
  claim: string;
  /** Source that produced this card (e.g. "declare_step", "PostToolUse"). */
  source: string;
  /**
   * Selectable options. Always includes one with id "bob" (Bob's claim).
   * May include alt-N alternatives generated by the companion LLM.
   */
  options: CardOption[];
}

/**
 * The developer's pick on a card:
 * - "bob" — agrees with Bob's claim
 * - an alt id (e.g. "alt-1") — disagrees, chose that alternative
 * - "other" — disagrees in their own words; text holds what they typed
 * - "ask_why" — wants Bob to explain before continuing
 */
export type AnswerPick = "bob" | "other" | "ask_why" | (string & {});

/** The developer's answer to a card. */
export interface AnswerRecord {
  kind: "answer";
  card: string;
  pick: AnswerPick;
  /** The chosen alternative text, or the developer's typed text for "other". */
  text?: string;
}

/**
 * A message delivered to Bob (from developer via the server).
 * card is absent when the message comes from the free-text box or the Hold button.
 */
export interface MessageRecord {
  kind: "message";
  id: string;
  card?: string;
  text: string;
  delivered_via: "mcp" | "hook";
  ts: string;
}

/** Bob's reply to a developer message or ask-why. */
export interface ReplyRecord {
  kind: "reply";
  card: string;
  text: string;
}
